#!/usr/bin/env node
// Precompiles components/*.jsx -> app.bundle.js (no runtime Babel).
// Order matters: Nav defines btnStyles/Glyph/Wordmark used by others; _App renders last.
// Cache-busts index.html with a content hash. Run: `node _tools/build.mjs`
// (the .githooks/pre-commit hook runs this automatically on commit).
import { readFileSync, writeFileSync } from 'fs';
import { createHash } from 'crypto';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { transformSync } from '@babel/core';
import presetReact from '@babel/preset-react';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Load order — must match dependency order (globals defined before use).
const ORDER = [
  'Nav', 'Hero', 'TrustBar', 'Manifesto', 'Staff', 'Program',
  'Materials', 'Proof', 'Pricing', 'Team', 'FAQ', 'Footer', '_App',
];

const parts = ORDER.map((name) => {
  const src = readFileSync(join(ROOT, 'components', `${name}.jsx`), 'utf8');
  const { code } = transformSync(src, {
    presets: [[presetReact, { runtime: 'classic' }]],
    filename: `${name}.jsx`,
    compact: false,
    comments: false,
  });
  return `/* ${name} */\n${code}`;
});

const banner = '/* GENERATED by _tools/build.mjs — DO NOT EDIT. Source: components/*.jsx */\n';
const bundle = banner + '(function(){\n"use strict";\n' + parts.join('\n') + '\n})();\n';
writeFileSync(join(ROOT, 'app.bundle.js'), bundle);

const hash = createHash('sha256').update(bundle).digest('hex').slice(0, 8);

// Inject the hashed bundle reference between markers in index.html.
const idxPath = join(ROOT, 'index.html');
let html = readFileSync(idxPath, 'utf8');
const tag = `<!-- BUNDLE --><script src="./app.bundle.js?v=${hash}"></script><!-- /BUNDLE -->`;
html = html.replace(/<!-- BUNDLE -->[\s\S]*?<!-- \/BUNDLE -->/, tag);
writeFileSync(idxPath, html);

console.log(`built app.bundle.js (${(bundle.length / 1024).toFixed(1)} KB) v=${hash}`);
